import assert from 'node:assert/strict';
import { recordingPackageJSON } from '../src/recording-package.js';
import { recordingState, recordingExitPolicy } from '../src/recording-guard.js';
const start = { session: { id: 'same', neuralRun: 1 }, createdAt: 'start', environment: { tempC: 24 } };
const end = { session: { id: 'same', neuralRun: 2 }, createdAt: 'end', environment: { tempC: 29 } };
const input = { csv: 'value\n1\n', rowCount: 1, start, end, samplingHz: 20, missedSamples: 0 };
const first = recordingPackageJSON(input);
assert.equal(recordingPackageJSON(input), first, 'retry produces byte-identical package');
const parsed = JSON.parse(first);
assert.equal(parsed.recording.csv, input.csv);
assert.equal(parsed.end.session.neuralRun, 2, 'recordings can span neural restarts');
assert.equal(parsed.start.environment.tempC, 24);
assert.equal(parsed.end.environment.tempC, 29);
assert.throws(() => recordingPackageJSON({ ...input, end: { session: { id: 'other' } } }));
assert.throws(() => recordingPackageJSON({ ...input, rowCount: 0 }));
assert.throws(() => recordingPackageJSON({ ...input, missedSamples: NaN }));
assert.equal(recordingExitPolicy(recordingState()), 'allow');
assert.equal(recordingExitPolicy(recordingState({ active: true })), 'confirm');
assert.equal(recordingExitPolicy(recordingState({ rows: 1 })), 'confirm');
assert.equal(recordingExitPolicy(recordingState({ saving: true, rows: 1 })), 'wait');
assert.deepEqual(recordingState({ active: 'yes', rows: NaN }), { active: false, saving: false, rows: 0 });
console.log('PASS self-contained recording packages, stable retry, session validation, exit/reload policy');
